/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package complaintsViews;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import controllers.ComplaintController;
import controllers.UserController;
import models.Complaint;
import models.User;
import utils.CustomizedException;

/**
*
* @author Steen
*/
public class DisplayTechnicianView extends javax.swing.JFrame {

   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

   public DisplayTechnicianView() {
       initComponents();
       addRowsToJTable();
   }

   public void addRowsToJTable() {
 	  DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//     Grab the returned array list and put it into a variable of type Arraylist
 	  UserController uc = new UserController();
 	  
 		  try {
				ArrayList <User> displayList = uc.getAllTechnicians();
				System.out.println("List successfully retrieved!");
				 Object rowData[] = new Object[5];
			        for (int i =0; i < displayList.size(); i++ ){
			            rowData[0] = displayList.get(i).getUserId();
			            rowData[1] = displayList.get(i).getFirstName();
			            rowData[2] = displayList.get(i).getLastName();
			            rowData[3] = displayList.get(i).getEmail();
			            rowData[4] = displayList.get(i).getContactNum();
			            
			         
			            model.addRow(rowData);
			        }
			} catch (CustomizedException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
   }
   
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jDialog1 = new javax.swing.JDialog();
       jDialog2 = new javax.swing.JDialog();
       jFrame1 = new javax.swing.JFrame();
       jDialog3 = new javax.swing.JDialog();
       jLabel1 = new javax.swing.JLabel();
       jScrollPane1 = new javax.swing.JScrollPane();
       jTable1 = new javax.swing.JTable();
       jButton1 = new javax.swing.JButton();
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });
       
       jTable1.setDragEnabled(false);
       jTable1.setEnabled(true);
       jTable1.getTableHeader().setReorderingAllowed(false);
       jTable1.getTableHeader().setResizingAllowed(false);
       
       javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
       jDialog1.getContentPane().setLayout(jDialog1Layout);
       jDialog1Layout.setHorizontalGroup(
           jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 400, Short.MAX_VALUE)
       );
       jDialog1Layout.setVerticalGroup(
           jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 300, Short.MAX_VALUE)
       );

       javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
       jDialog2.getContentPane().setLayout(jDialog2Layout);
       jDialog2Layout.setHorizontalGroup(
           jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 400, Short.MAX_VALUE)
       );
       jDialog2Layout.setVerticalGroup(
           jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 300, Short.MAX_VALUE)
       );

       javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
       jFrame1.getContentPane().setLayout(jFrame1Layout);
       jFrame1Layout.setHorizontalGroup(
           jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 400, Short.MAX_VALUE)
       );
       jFrame1Layout.setVerticalGroup(
           jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 300, Short.MAX_VALUE)
       );

       javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
       jDialog3.getContentPane().setLayout(jDialog3Layout);
       jDialog3Layout.setHorizontalGroup(
           jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 400, Short.MAX_VALUE)
       );
       jDialog3Layout.setVerticalGroup(
           jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 300, Short.MAX_VALUE)
       );

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
       setBackground(new java.awt.Color(255, 255, 255));

       jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
       jLabel1.setText("Technician Information");

       jTable1.setModel(new javax.swing.table.DefaultTableModel(
           new Object [][] {

           },
           new String [] {
               "User Id", "First Name", "Last Name", "Email", "Contact Number"
           }
       ));
       jScrollPane1.setViewportView(jTable1);

       jButton1.setText("OK");

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jScrollPane1)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap(283, Short.MAX_VALUE)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(276, 276, 276))
           .addGroup(layout.createSequentialGroup()
               .addGap(365, 365, 365)
               .addComponent(jButton1)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jButton1)
               .addContainerGap(22, Short.MAX_VALUE))
       );

       pack();
   }// </editor-fold>                        

   
   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       this.dispose();
    }
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(DisplayTechnicianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(DisplayTechnicianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(DisplayTechnicianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(DisplayTechnicianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new DisplayTechnicianView().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1;
   private javax.swing.JDialog jDialog1;
   private javax.swing.JDialog jDialog2;
   private javax.swing.JDialog jDialog3;
   private javax.swing.JFrame jFrame1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable jTable1;
   // End of variables declaration                     
}
