package complaintsViews;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;


import controllers.ResponseController;
import models.Response;
import utils.CustomizedException;

public class DisplayResponsesView extends javax.swing.JFrame {

	    /**
		 * 
		 */
		private static final long serialVersionUID = 1L;
		/**
	     * Creates new form NewJFrame2
	     */
	    public DisplayResponsesView() {
	        initComponents();
	        addRowsToJTable();
	    }

	    public void addRowsToJTable() {
	    	DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//	        Grab the returned array list and put it into a variable of type Arraylist
	    	  ResponseController rc = new ResponseController();
	    	 
	    		  try {
	    			  int complaintId = 36;
	  				ArrayList <Response> displayList = rc.getResponsesPerUser(complaintId);
	  				System.out.println("List successfully retrieved!");
	  				 Object rowData[] = new Object[4];
	  			        for (int i =0; i < displayList.size(); i++ ){
	  			       
	  			        	rowData[0] = displayList.get(i).getResponse_id();
	  			        	rowData[1] = displayList.get(i).getComplaint_id();
	  			        	rowData[2] = displayList.get(i).getResponse_date();
	  			        	rowData[3] = displayList.get(i).getResponse();
	  			        	
	  			            model.addRow(rowData);    
	  			           		            
	  			        }
	  			} catch (CustomizedException e1) {
	  				// TODO Auto-generated catch block
	  				e1.printStackTrace();
	  			}
	  			
	    	 
	    }
	    
	    
	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jScrollPane1 = new javax.swing.JScrollPane();
	        jTable1 = new javax.swing.JTable();
	        jButton1 = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

	        jTable1.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {

	            },
	            new String [] {
	                "Response Id", "Complaint Id", "Response Date", "Response"
	            }
	   
	        ));
	        jScrollPane1.setViewportView(jTable1);

	        jButton1.setText("OK");
	        

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(369, 369, 369)
	                .addComponent(jButton1)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
	                .addGap(18, 18, 18)
	                .addComponent(jButton1)
	                .addGap(20, 20, 20))
	        );
	        
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });
	        
	        pack();
	    }// </editor-fold>                        

	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        this.dispose();
	    }            

	    
	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(DisplayResponsesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(DisplayResponsesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(DisplayResponsesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(DisplayResponsesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        
	        
	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new DisplayResponsesView().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JTable jTable1;
	    // End of variables declaration         
}
