/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package complaintsViews;

import javax.swing.JOptionPane;

/**
*
* @author Steen
*/
public class NewJFrame2 extends javax.swing.JFrame {

   /**
    * Creates new form NewJFrame2
    */
   public NewJFrame2() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jLabel1 = new javax.swing.JLabel();
       jButton1 = new javax.swing.JButton();
       jTextField1 = new javax.swing.JTextField();
       jTextField1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField1ActionPerformed(evt);
           }
       });
       
       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
       jLabel1.setText("Enter the Technician Id below");

       jButton1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
       jButton1.setText("Assign");

       jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(51, 51, 51)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(26, 26, 26)
                       .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addContainerGap(49, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(32, 32, 32)
               .addComponent(jLabel1)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(46, Short.MAX_VALUE))
       );

       pack();
   }// </editor-fold>                        

   
   private void jTextField1ActionPerformed(java.awt.event.ActionEvent e) {                                            
   	if(e.getSource() == jTextField1) {

			if (jTextField1.getText().equals("")){
          	 JOptionPane.showMessageDialog(NewJFrame2.this,
        			  	"You cannot submit an empty value.\nPlease try again.",
        			    "Search Complaint Status",
        			    JOptionPane.ERROR_MESSAGE);
           } else {
           	try {
					if (Integer.parseInt(jTextField1.getText()) > 0) {
			           	int input = Integer.parseInt(jTextField1.getText()); 
						System.out.println("Search Complaint Input: "+input);
						try {
							JOptionPane.showMessageDialog(NewJFrame2.this,
								  	"Technician was added successfully",
								    "Complaint Tool Tip",
								    JOptionPane.INFORMATION_MESSAGE);
						} catch (NullPointerException npe) {
							JOptionPane.showMessageDialog(NewJFrame2.this,
								  	"Technician not found in database",
								    "Complaint Tool Tip",
								    JOptionPane.ERROR_MESSAGE);
						}
					} else if (Integer.parseInt(jTextField1.getText()) < 0) {
		           	  JOptionPane.showMessageDialog(NewJFrame2.this,
						  	"Invalid input.\nId number must not be negative number."
						  	+ "\nPlease try again.",
						    "Complaint Tool Tip",
						    JOptionPane.WARNING_MESSAGE);
		           	  
		             } else if (Integer.parseInt(jTextField1.getText()) == 0) {
		            	 	JOptionPane.showMessageDialog(NewJFrame2.this,
							  	"Invalid input.\nId number must not be equal to zero."
							  	+ "\nPlease try again.",
							    "Complaint Tool Tip",
							    JOptionPane.WARNING_MESSAGE);
		            	
		             } 
				 
	            } catch (NumberFormatException e2) {
	            	JOptionPane.showMessageDialog(NewJFrame2.this,
	         			  	"You cannot submit letters.\nPlease try again.",
	         			    "Complaint Tool Tip",
	         			    JOptionPane.ERROR_MESSAGE);
	            	
	            }
           }

		}	
   }       
   
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new NewJFrame2().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JTextField jTextField1;
   // End of variables declaration                                     
}
